name: C/C++ CI

on:
  push:
    branches: [ "custom" ]
  pull_request:
    branches: [ "custom" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libinput-dev \
          libwayland-dev \
          libxkbcommon-dev \
          wayland-protocols \
          pkg-config \
          libxcb1-dev \
          libxcb-util-dev \
          libxcb-ewmh-dev \
          libxcb-keysyms1-dev \
          libxcb-icccm4-dev \
          libxcb-wm-dev \
          xwayland \
          wlroots
#    - name: configure
#      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
